#!/bin/php
<?php
declare(strict_types=1);

namespace Challenge;

require 'src/Player.php';
require 'src/Game.php';

if (!isset($argv[2])) {
    die("usage: play.php <player1> <player2> [--debug]\n");
}
$script1 = 'players/'.$argv[1].'/battle.php';
$script2 = 'players/'.$argv[2].'/battle.php';

if (!file_exists($script1)) {
    die("Could not found {$script1}\n");
}
if (!file_exists($script2)) {
    die("Could not found {$script1}\n");
}

$debug = \in_array('--debug', $argv, true);
$iterations = 1;
if (is_numeric($argv[3] ?? null)) {
    $iterations = (int)$argv[3];
} elseif (is_numeric($a[4] ?? null)) {
    $iterations = (int)$argv[4];
}

$turns = 0;
$perf = [
    $argv[1] => 0,
    $argv[2] => 0,
];
$count = 0;

while ($iterations--) {
    $game = new Game(
        new Player($argv[1], $script1, $debug),
        new Player($argv[2], $script2, $debug),
        60
    );
    $stats = $game->play();
    $count++;
    $turns += $stats['turns'];
    $perf[$argv[1]] += $stats[$argv[1]];
    $perf[$argv[2]] += $stats[$argv[2]];
    if (isset($stats['error'])) {
        echo $stats['error'], "\n";
    }
}
echo "\n";
echo "turns AVG: ", round($turns / $count / 2), "\n";
echo "perf ", $argv[1], ": ", round($perf[$argv[1]] / $count * 1000000), "µs\n";
echo "perf ", $argv[2], ": ", round($perf[$argv[2]] / $count * 1000000), "µs\n";
